on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'

name: rector

jobs:
  rector:
    uses: yiisoft/actions/.github/workflows/rector.yml@master
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      os: >-
        ['ubuntu-latest']
      php: >-
        ['7.4']
